apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx-ns
  labels:
    app: nginx-pod
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-pod
  template:
    metadata:
      namespace: nginx-ns
      labels:
        app: nginx-pod
    spec:
       containers:
        - name: nginx-pod
          image: nginx:latest
          ports:
            - containerPort: 80

